version: "2.3"
services:
  portal:
    image: harbor.9itest.com/ecsp/interaction-class-portal:1.0-SNAPSHOT
    ports:
      - "80:80"
    container_name: interaction-class-portal
    networks:
      - portal
    mem_limit: 500m
    environment:
      API_SERVER_01: 10.5.52.91:8888
      API_SERVER_02: 10.5.52.91:8888
      PORTAL_SERVER_PORT: 80
networks:
  portal:
    driver: bridge
